name: auto generate new websites

on: [pull_request]

jobs:
  generate:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: generate websites
      run: node handleWebsites.js
      
    - name: Auto Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        COMMIT_MESSAGE: "chore: auto generate new websites"
        COMMIT_AUTHOR_EMAIL: "liubiantao@gmail.com"
        COMMIT_AUTHOR_NAME: "liubiantao"

        
